# Generated by Django 3.2.7 on 2021-09-28 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=50, verbose_name='Category')),
                ('HSNCode', models.CharField(max_length=10, verbose_name='HSN Code')),
                ('TaxPercentage', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Tax Percentage')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('CityId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=50, verbose_name='City')),
            ],
        ),
        migrations.CreateModel(
            name='GSTwiseSummary',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('InvoiceNo', models.CharField(max_length=10, verbose_name='Invoice No')),
                ('GSTAmnt', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='GST Amount')),
                ('CGSTAmnt', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='CGST Amount')),
                ('SGTAmnt', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='SGST Amount')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('PartyId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('PartyName', models.CharField(max_length=100, verbose_name='Supplier')),
                ('GSTNNo', models.CharField(max_length=17, verbose_name='GSTN No')),
                ('Shop', models.CharField(max_length=100, verbose_name='Shop Address')),
                ('PartyType', models.CharField(max_length=10, verbose_name='Supplier Type')),
                ('IsActive', models.IntegerField(default=1, verbose_name='Is Active')),
                ('City', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchaseapp.city')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('PaymentMode', models.CharField(max_length=20, verbose_name='Pay Mode')),
                ('PayeeName', models.CharField(max_length=50, verbose_name='Name of Payee')),
                ('CardNo', models.CharField(max_length=25, verbose_name='Card Number')),
                ('ExpDate', models.DateField(verbose_name='Expiry Date')),
                ('Code', models.CharField(max_length=3, verbose_name='Secuirity code')),
                ('Chequeno', models.CharField(max_length=50, verbose_name='Cheque No')),
                ('BankBranch', models.CharField(max_length=100, verbose_name='Bank Branch')),
                ('MobileNo', models.CharField(max_length=15, verbose_name='Mobile Number')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100, verbose_name='Item')),
                ('ProductCode', models.CharField(max_length=15, verbose_name='Item Code')),
                ('ReorderLevel', models.IntegerField(verbose_name='Reorder Level')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('StateId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('StateName', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('StateCode', models.IntegerField(verbose_name='State Code')),
                ('StateAbbr', models.CharField(max_length=10, verbose_name='State Abbr')),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Uomtype', models.CharField(max_length=25, verbose_name='UOM')),
                ('UomCode', models.CharField(max_length=10, verbose_name='UOM Code')),
            ],
        ),
        migrations.CreateModel(
            name='StockTable',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('StockQty', models.IntegerField(verbose_name='Stock Quantity')),
                ('BaseUOM', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchaseapp.uom')),
                ('ProductName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseMaster',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('InvoiceNo', models.CharField(max_length=25, verbose_name='Invoice No')),
                ('Remarks', models.TextField(max_length=250)),
                ('InvoiceDate', models.DateField(verbose_name='Invoice Date')),
                ('Type', models.CharField(max_length=25, verbose_name='Purchase Type')),
                ('TaxableAmt', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Taxable Amount')),
                ('CGSTAmnt', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='CGST Amount')),
                ('SGSTAmnt', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='SGST Amount')),
                ('IGSTAmnt', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='IGST Amount')),
                ('Subtotal', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Purchase Subtotal')),
                ('Discount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Purchase Discount')),
                ('GrantTotal', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Purchase GrantTotal')),
                ('Paymode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseapp.paymentdetails')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseapp.state', verbose_name='Purchase State')),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchaseapp.party')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Quantity', models.IntegerField(verbose_name='Qty')),
                ('Rate', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Disc', models.CharField(blank=True, max_length=10, null=True)),
                ('Taxable', models.DecimalField(decimal_places=3, max_digits=10)),
                ('Tax', models.DecimalField(decimal_places=3, max_digits=10)),
                ('CGST', models.DecimalField(decimal_places=3, max_digits=10)),
                ('SGST', models.DecimalField(decimal_places=3, max_digits=10)),
                ('IGST', models.DecimalField(decimal_places=3, max_digits=10)),
                ('BaseQty', models.IntegerField(verbose_name='Base Qty')),
                ('Amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('HSNCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseapp.category', verbose_name='HSN Code')),
                ('Item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseapp.product')),
                ('UOM', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchaseapp.uom')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='BaseUOM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseapp.uom', verbose_name='Base UOM'),
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseapp.category'),
        ),
        migrations.AddField(
            model_name='party',
            name='State',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseapp.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='StateCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseapp.state'),
        ),
    ]
