# Generated by Django 3.2.7 on 2021-09-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseapp', '0002_rename_statecode_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='IsActive',
        ),
    ]
