# Generated by Django 3.2.7 on 2021-10-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseapp', '0005_auto_20210930_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentmode',
            fields=[
                ('Id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('PaymentMode', models.CharField(blank=True, max_length=25, null=True, verbose_name='Payment mode')),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='HSNCode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='HSN Code'),
        ),
        migrations.AlterField(
            model_name='category',
            name='TaxPercentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Tax Percentage'),
        ),
        migrations.AlterField(
            model_name='city',
            name='CityName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='gstwisesummary',
            name='CGSTAmnt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='CGST Amount'),
        ),
        migrations.AlterField(
            model_name='gstwisesummary',
            name='GSTAmnt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='GST Amount'),
        ),
        migrations.AlterField(
            model_name='gstwisesummary',
            name='InvoiceNo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Invoice No'),
        ),
        migrations.AlterField(
            model_name='gstwisesummary',
            name='SGTAmnt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='SGST Amount'),
        ),
        migrations.AlterField(
            model_name='party',
            name='GSTNNo',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='GSTN No'),
        ),
        migrations.AlterField(
            model_name='party',
            name='PartyType',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Supplier Type'),
        ),
        migrations.AlterField(
            model_name='party',
            name='Shop',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shop Address'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='BankBranch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Branch'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='CardNo',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Card Number'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='Chequeno',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cheque No'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='Code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Secuirity code'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='ExpDate',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='MobileNo',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='PayeeName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name of Payee'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='PaymentMode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pay Mode'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductCode',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Item Code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ReorderLevel',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reorder Level'),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='Amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='BaseQty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Base Qty'),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='CGST',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='IGST',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='Quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qty'),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='Rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='SGST',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='Tax',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='Taxable',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedetails',
            name='UOM',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchaseapp.uom'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='CGSTAmnt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='CGST Amount'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='Discount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Purchase Discount'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='GrantTotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Purchase GrantTotal'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='IGSTAmnt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='IGST Amount'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='InvoiceDate',
            field=models.DateField(blank=True, null=True, verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='Item',
            field=models.ManyToManyField(blank=True, null=True, related_name='PurchaseMaster', through='purchaseapp.PurchaseDetails', to='purchaseapp.Product'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='Remarks',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='SGSTAmnt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='SGST Amount'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='State',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseapp.state', verbose_name='Purchase State'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='Subtotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Purchase Subtotal'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='Supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseapp.party'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='TaxableAmt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Taxable Amount'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='Type',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Purchase Type'),
        ),
        migrations.AlterField(
            model_name='state',
            name='StateAbbr',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='State Abbr'),
        ),
        migrations.AlterField(
            model_name='state',
            name='StateCode',
            field=models.IntegerField(blank=True, null=True, verbose_name='State Code'),
        ),
        migrations.AlterField(
            model_name='stocktable',
            name='ProductName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseapp.product'),
        ),
        migrations.AlterField(
            model_name='stocktable',
            name='StockQty',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='uom',
            name='UomCode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='UOM Code'),
        ),
    ]
