# Generated by Django 3.2.7 on 2021-10-01 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseapp', '0006_auto_20211001_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='PaymentMode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchaseapp.paymentmode', verbose_name='Pay Mode'),
        ),
    ]
