# Generated by Django 3.2.7 on 2021-10-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseapp', '0009_auto_20211005_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductPrice',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
